# Generated by Django 4.0.3 on 2022-03-07 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Annonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('details', models.TextField()),
                ('mise_en_ligne', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
